Game:
  SteamId: "1066890"
  Path: steamapps\common\Automobilista 2
  ProcessName: AMS2AVX
ModInstall:
  DirsAtRoot:
  - cameras
  - characters
  - effects
  - gui
  - pakfiles
  - render
  - text
  - tracks
  - userdata
  - upgrade
  - vehicles
  ExcludedFromConfig:
  # IndyCar 2023 1.0 Fix
  - '**\IR-18_2023_Dale_Coyne_hr.crd'
  # IndyCar 2023 Optional Entries
  #- '**\IR-18_2023_Abel*'
  #- '**\IR-18_2023_Dreyer_Reinbold*'
  #- '**\IR-18_2023_My_Team*'
