name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-latest
    permissions:
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Configure NuGet repository
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OpenSimTools/index.json"

    - name: Build
      run: dotnet build AMS2CM.sln --configuration ${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}

    - name: Test
      run: dotnet test tests/Core.Tests/Core.Tests.csproj --configuration ${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} --no-build --no-restore

    - name: Upload CLI
      uses: actions/upload-artifact@v7
      with:
        name: AMS2CM CLI
        path: |
            src/CLI/bin/${{ matrix.platform }}/${{ matrix.configuration }}/net10.0-windows/**
            LICENSE
        if-no-files-found: error
    # Separate package until stable, to be able to release CLI independently
    - name: Upload Installer
      uses: actions/upload-artifact@v7
      with:
        name: AMS2CM
        path: src/Installer/bin/${{ matrix.platform }}/${{ matrix.configuration }}/AMS2CM.msi
        if-no-files-found: error
