name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-latest
    permissions:
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Configure NuGet repository
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OpenSimTools/index.json"

    - name: Build
      run: |
        msbuild /t:Restore /p:Configuration=${{ matrix.configuration }}
        msbuild /t:Build /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
        dotnet test --configuration ${{ matrix.configuration }} --arch ${{ matrix.platform }}

    - name: Upload CLI
      uses: actions/upload-artifact@v4
      with:
        name: AMS2CM CLI
        path: |
            src/CLI/bin/${{ matrix.platform }}/${{ matrix.configuration }}/net6.0-windows/**
            LICENSE
        if-no-files-found: error
    # Separate package until stable, to be able to release CLI independently
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: AMS2CM
        path: src/Installer/bin/${{ matrix.platform }}/${{ matrix.configuration }}/AMS2CM.msi
        if-no-files-found: error
