name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet publish
      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: AMS2CM
          path: src/CLI/bin/Debug/net6.0-windows/publish/**
          if-no-files-found: error
      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: AMS2CM
          path: LICENSE
          if-no-files-found: error
