name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-latest
    permissions:
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Configure NuGet repository
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OpenSimTools/index.json"

    - name: Build
      run: |
        msbuild /t:Restore /p:Configuration=${{ matrix.configuration }}
        msbuild /t:Publish /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Upload license
      uses: actions/upload-artifact@v3
      with:
        name: AMS2CM
        path: LICENSE
        if-no-files-found: error
    - name: Upload CLI
      uses: actions/upload-artifact@v3
      with:
        name: AMS2CM
        path: src/CLI/bin/${{ matrix.configuration }}/net6.0-windows/publish/**
        if-no-files-found: error
    # Separate package until stable, to be able to release CLI independently
    - name: Upload GUI
      uses: actions/upload-artifact@v3
      with:
        name: AMS2CM GUI
        path: src/GUI/bin/${{ matrix.platform }}/${{ matrix.configuration }}/net6.0-windows10.0.19041.0/**
        if-no-files-found: error
